apiVersion: v1
kind: ConfigMap
metadata:
  name: "configmap-{{ .Values.version }}"
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
      <body>
        <h1>test page {{ .Values.version }}</h1>
        <p>HTML file {{ .Values.version }}</p>
      </body>
    </html>
