apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources: # these limits exceed limit range defined in 'limit-range.yml'
        limits:
          cpu: "1500m"
        requests:
          cpu: "1500m"
