apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wget-echo-server-service-cronjob
spec:
  schedule: "*/3 * * * *" # every 3 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox:latest
              command:
                - /bin/sh
                - -c
                - wget echo-server-service.default.svc.cluster.local
          restartPolicy: OnFailure
