apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: LoadBalancer
  selector:
    app: apache # The actual fix is to match labels in deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # The actual fix is to map expected ports
